version: 2
jobs:
  test:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "68:4b:af:b0:a6:5e:d6:59:a1:ee:bf:12:36:9d:7d:fc"
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn lint
      - run: yarn test
  release:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
workflows:
  version: 2
  do_build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - release:
          context: private_packages
          filters:
            branches:
              only:
                - dev
                - stage
                - main